service: serverless-capital-one-app

provider:
  name: aws
  runtime: nodejs12.x

functions:
  captialOneApplication:
    handler: index.handler
    name: serverless-capital-one-app
    events:
      - http:
          path: daily/total
          method: get
      - http:
          path: daily/top/transactions
          method: get
      - http:
          path: getPurchases/{accountId}
          method: get
          request:
            parameters:
              paths:
                accountId: true
