service: serverless-capital-one-app

provider:
  name: aws
  runtime: nodejs12.x

functions:
  captialOneApplication:
    handler: index.handler
    name: serverless-capital-one-app
    timeout: 120
    events:
      - http: # Daily Top for 1 week
          path: purchases/{accountId}/daily/top
          method: get
          request:
            parameters:
              paths:
                accountId: true
      - http:
          path: getPurchases/{accountId}
          method: get
          request:
            parameters:
              paths:
                accountId: true
      - http: # Generate Purchases
          path: purchases/{accountId}/generate
          method: put
          request:
            parameters:
              paths:
                accountId: true
